# Makefile for CNSS platform driver

cnsscore-objs	+= ../wcnss/qcomwlan_secif.o
obj-$(CONFIG_CNSS)	+= wlan_firmware_service_v01.o
obj-$(CONFIG_CNSS)	+= cnsscore.o
obj-$(CONFIG_CNSS)	+= cnss_sdio.o
obj-$(CONFIG_CNSS)	+= cnss_pci.o
obj-$(CONFIG_CNSS)	+= cnss_common.o
