# SPDX-License-Identifier: GPL-2.0

icc-osm-l3-objs			:= osm-l3.o
qnoc-qcs404-objs			:= qcs404.o
qnoc-scshrike-objs			:= scshrike.o
qnoc-sdm845-objs			:= sdm845.o
qnoc-lahaina-objs			:= lahaina.o qnoc-qos.o
qnoc-sdxlemur-objs			:= sdxlemur.o qnoc-qos.o
qnoc-shima-objs			:= shima.o
qnoc-sm8150-objs			:= sm8150.o
icc-smd-rpm-objs			:= smd-rpm.o
icc-bcm-voter-objs			:= bcm-voter.o
icc-rpmh-obj				:= icc-rpmh.o

obj-$(CONFIG_INTERCONNECT_QCOM_OSM_L3) += icc-osm-l3.o
obj-$(CONFIG_INTERCONNECT_QCOM_QCS404) += qnoc-qcs404.o
obj-$(CONFIG_INTERCONNECT_QCOM_SCSHRIKE) += qnoc-scshrike.o
obj-$(CONFIG_INTERCONNECT_QCOM_SDM845) += qnoc-sdm845.o
obj-$(CONFIG_INTERCONNECT_QCOM_SM8150) += qnoc-sm8150.o
obj-$(CONFIG_INTERCONNECT_QCOM_LAHAINA) += qnoc-lahaina.o
obj-$(CONFIG_INTERCONNECT_QCOM_SDXLEMUR) += qnoc-sdxlemur.o
obj-$(CONFIG_INTERCONNECT_QCOM_SMD_RPM) += icc-smd-rpm.o
obj-$(CONFIG_INTERCONNECT_QCOM_BCM_VOTER) += icc-bcm-voter.o
obj-$(CONFIG_INTERCONNECT_QCOM_RPMH) += icc-rpmh.o
obj-$(CONFIG_INTERCONNECT_QCOM_EPSS_L3) += epss-l3.o
