/* Copyright (c) 2014, The Linux Foundation. All rights reserved.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 and
 * only version 2 as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */

#ifndef __MSM_CLOCKS_THULIUM_H
#define __MSM_CLOCKS_THULIUM_H

/* clock_gcc controlled clocks */
#define clk_cxo_clk_src			&cxo_clk_src
#define clk_pnoc_clk			&pnoc_clk
#define clk_pnoc_a_clk			&pnoc_a_clk
#define clk_bimc_clk			&bimc_clk
#define clk_bimc_a_clk			&bimc_a_clk
#define clk_cnoc_clk			&cnoc_clk
#define clk_cnoc_a_clk			&cnoc_a_clk
#define clk_snoc_clk			&snoc_clk
#define clk_snoc_a_clk			&snoc_a_clk
#define clk_bb_clk1			&bb_clk1
#define clk_bb_clk1_ao			&bb_clk1_ao
#define clk_bb_clk1_pin			&bb_clk1_pin
#define clk_bb_clk1_pin_ao		&bb_clk1_pin_ao
#define clk_bb_clk2			&bb_clk2
#define clk_bb_clk2_ao			&clk_bb_clk2_ao
#define clk_bb_clk2_pin			&bb_clk2_pin
#define clk_bb_clk2_pin_ao		&bb_clk2_pin_ao
#define clk_bimc_msmbus_clk		&bimc_msmbus_clk
#define clk_bimc_msmbus_a_clk		&bimc_msmbus_a_clk
#define clk_ce1_a_clk			&ce1_a_clk
#define clk_cnoc_msmbus_clk		&cnoc_msmbus_clk
#define clk_cnoc_msmbus_a_clk		&cnoc_msmbus_a_clk
#define clk_cxo_clk_src_ao		&cxo_clk_src_ao
#define clk_cxo_dwc3_clk		&cxo_dwc3_clk
#define clk_cxo_lpm_clk			&cxo_lpm_clk
#define clk_cxo_otg_clk			&cxo_otg_clk
#define clk_cxo_pil_lpass_clk		&cxo_pil_lpass_clk
#define clk_div_clk1			&div_clk1
#define clk_div_clk1_ao			&div_clk1_ao
#define clk_div_clk2			&div_clk2
#define clk_div_clk2_ao			&div_clk2_ao
#define clk_div_clk3			&div_clk3
#define clk_div_clk3_ao			&div_clk3_ao
#define clk_ipa_clk			&ipa_clk
#define clk_ipa_a_clk			&ipa_a_clk
#define clk_ln_bb_clk			&ln_bb_clk
#define clk_ln_bb_a_clk			&ln_bb_a_clk
#define clk_pnoc_keepalive_a_clk	&pnoc_keepalive_a_clk
#define clk_pnoc_msmbus_clk		&pnoc_msmbus_clk
#define clk_pnoc_msmbus_a_clk		&pnoc_msmbus_a_clk
#define clk_pnoc_pm_clk			&pnoc_pm_clk
#define clk_pnoc_sps_clk		&pnoc_sps_clk
#define clk_qdss_clk			&qdss_clk
#define clk_qdss_a_clk			&qdss_a_clk
#define clk_rf_clk1			&rf_clk1
#define clk_rf_clk1_ao			&rf_clk1_ao
#define clk_rf_clk1_pin			&rf_clk1_pin
#define clk_rf_clk1_pin_ao		&rf_clk1_pin_ao
#define clk_rf_clk2			&rf_clk2
#define clk_rf_clk2_ao			&rf_clk2_ao
#define clk_rf_clk2_pin			&rf_clk2_pin
#define clk_rf_clk2_pin_ao		&rf_clk2_pin_ao
#define clk_snoc_msmbus_clk		&snoc_msmbus_clk
#define clk_snoc_msmbus_a_clk		&snoc_msmbus_a_clk
#define clk_mcd_ce1_clk			&mcd_ce1_clk
#define clk_qcedev_ce1_clk		&qcedev_ce1_clk
#define clk_qcrypto_ce1_clk		&qcrypto_ce1_clk
#define clk_qseecom_ce1_clk		&qseecom_ce1_clk
#define clk_scm_ce1_clk			&scm_ce1_clk
#define clk_ce1_clk			&ce1_clk
#define clk_gcc_ce1_ahb_m_clk		&gcc_ce1_ahb_m_clk
#define clk_gcc_ce1_axi_m_clk		&gcc_ce1_axi_m_clk
#define clk_gcc_mmss_bimc_gfx_m_clk	&gcc_mmss_bimc_gfx_m_clk
#define clk_aggre1_noc_clk		&aggre1_noc_clk
#define clk_aggre1_noc_a_clk		&aggre1_noc_a_clk
#define clk_aggre2_noc_clk		&aggre2_noc_clk
#define clk_aggre2_noc_a_clk		&aggre2_noc_a_clk
#define clk_rpm_debug_mux		&rpm_debug_mux

#define clk_gcc_xo			&gcc_xo
#define clk_gcc_xo_a_clk		&gcc_xo_a_clk
#define clk_debug_mmss_clk		&debug_mmss_clk
#define clk_debug_rpm_clk		&debug_rpm_clk
#define clk_gpll0_out_main		&gpll0_out_main
#define clk_gpll4_out_main		&gpll4_out_main
#define clk_gpll2_out_main		&gpll2_out_main
#define clk_gpll3_out_main		&gpll3_out_main
#define clk_gpll1_out_main		&gpll1_out_main
#define clk_ufs_axi_clk_src		&ufs_axi_clk_src
#define clk_pcie_aux_clk_src		&pcie_aux_clk_src
#define clk_sys_noc_hs_axi_clk_src	&sys_noc_hs_axi_clk_src
#define clk_usb30_master_clk_src	&usb30_master_clk_src
#define clk_usb20_master_clk_src	&usb20_master_clk_src
#define clk_ufs_ice_core_clk_src	&ufs_ice_core_clk_src
#define clk_blsp1_qup1_i2c_apps_clk_src &blsp1_qup1_i2c_apps_clk_src
#define clk_blsp1_qup1_spi_apps_clk_src &blsp1_qup1_spi_apps_clk_src
#define clk_blsp1_qup2_i2c_apps_clk_src &blsp1_qup2_i2c_apps_clk_src
#define clk_blsp1_qup2_spi_apps_clk_src &blsp1_qup2_spi_apps_clk_src
#define clk_blsp1_qup3_i2c_apps_clk_src &blsp1_qup3_i2c_apps_clk_src
#define clk_blsp1_qup3_spi_apps_clk_src &blsp1_qup3_spi_apps_clk_src
#define clk_blsp1_qup4_i2c_apps_clk_src &blsp1_qup4_i2c_apps_clk_src
#define clk_blsp1_qup4_spi_apps_clk_src &blsp1_qup4_spi_apps_clk_src
#define clk_blsp1_qup5_i2c_apps_clk_src &blsp1_qup5_i2c_apps_clk_src
#define clk_blsp1_qup5_spi_apps_clk_src &blsp1_qup5_spi_apps_clk_src
#define clk_blsp1_qup6_i2c_apps_clk_src &blsp1_qup6_i2c_apps_clk_src
#define clk_blsp1_qup6_spi_apps_clk_src &blsp1_qup6_spi_apps_clk_src
#define clk_blsp1_uart1_apps_clk_src	&blsp1_uart1_apps_clk_src
#define clk_blsp1_uart2_apps_clk_src	&blsp1_uart2_apps_clk_src
#define clk_blsp1_uart3_apps_clk_src	&blsp1_uart3_apps_clk_src
#define clk_blsp1_uart4_apps_clk_src	&blsp1_uart4_apps_clk_src
#define clk_blsp1_uart5_apps_clk_src	&blsp1_uart5_apps_clk_src
#define clk_blsp1_uart6_apps_clk_src	&blsp1_uart6_apps_clk_src
#define clk_blsp2_qup1_i2c_apps_clk_src &blsp2_qup1_i2c_apps_clk_src
#define clk_blsp2_qup1_spi_apps_clk_src &blsp2_qup1_spi_apps_clk_src
#define clk_blsp2_qup2_i2c_apps_clk_src &blsp2_qup2_i2c_apps_clk_src
#define clk_blsp2_qup2_spi_apps_clk_src &blsp2_qup2_spi_apps_clk_src
#define clk_blsp2_qup3_i2c_apps_clk_src &blsp2_qup3_i2c_apps_clk_src
#define clk_blsp2_qup3_spi_apps_clk_src &blsp2_qup3_spi_apps_clk_src
#define clk_blsp2_qup4_i2c_apps_clk_src &blsp2_qup4_i2c_apps_clk_src
#define clk_blsp2_qup4_spi_apps_clk_src &blsp2_qup4_spi_apps_clk_src
#define clk_blsp2_qup5_i2c_apps_clk_src &blsp2_qup5_i2c_apps_clk_src
#define clk_blsp2_qup5_spi_apps_clk_src &blsp2_qup5_spi_apps_clk_src
#define clk_blsp2_qup6_i2c_apps_clk_src &blsp2_qup6_i2c_apps_clk_src
#define clk_blsp2_qup6_spi_apps_clk_src &blsp2_qup6_spi_apps_clk_src
#define clk_blsp2_uart1_apps_clk_src	&blsp2_uart1_apps_clk_src
#define clk_blsp2_uart2_apps_clk_src	&blsp2_uart2_apps_clk_src
#define clk_blsp2_uart3_apps_clk_src	&blsp2_uart3_apps_clk_src
#define clk_blsp2_uart4_apps_clk_src	&blsp2_uart4_apps_clk_src
#define clk_blsp2_uart5_apps_clk_src	&blsp2_uart5_apps_clk_src
#define clk_blsp2_uart6_apps_clk_src	&blsp2_uart6_apps_clk_src
#define clk_gp1_clk_src			&gp1_clk_src
#define clk_gp2_clk_src			&gp2_clk_src
#define clk_gp3_clk_src			&gp3_clk_src
#define clk_pdm2_clk_src		&pdm2_clk_src
#define clk_sdcc1_apps_clk_src		&sdcc1_apps_clk_src
#define clk_sdcc2_apps_clk_src		&sdcc2_apps_clk_src
#define clk_sdcc3_apps_clk_src		&sdcc3_apps_clk_src
#define clk_sdcc4_apps_clk_src		&sdcc4_apps_clk_src
#define clk_tsif_ref_clk_src		&tsif_ref_clk_src
#define clk_usb20_mock_utmi_clk_src	&usb20_mock_utmi_clk_src
#define clk_usb30_mock_utmi_clk_src	&usb30_mock_utmi_clk_src
#define clk_usb3_phy_aux_clk_src	&usb3_phy_aux_clk_src
#define clk_gcc_qusb2phy_prim_reset	&gcc_qusb2phy_prim_reset
#define clk_gcc_usb3_phy_reset		&gcc_usb3_phy_reset
#define clk_gcc_usb3phy_phy_reset	&gcc_usb3phy_phy_reset
#define clk_gcc_blsp1_ahb_clk		&gcc_blsp1_ahb_clk
#define clk_gcc_blsp1_qup1_i2c_apps_clk	&gcc_blsp1_qup1_i2c_apps_clk
#define clk_gcc_blsp1_qup1_spi_apps_clk	&gcc_blsp1_qup1_spi_apps_clk
#define clk_gcc_blsp1_qup2_i2c_apps_clk	&gcc_blsp1_qup2_i2c_apps_clk
#define clk_gcc_blsp1_qup2_spi_apps_clk	&gcc_blsp1_qup2_spi_apps_clk
#define clk_gcc_blsp1_qup3_i2c_apps_clk	&gcc_blsp1_qup3_i2c_apps_clk
#define clk_gcc_blsp1_qup3_spi_apps_clk	&gcc_blsp1_qup3_spi_apps_clk
#define clk_gcc_blsp1_qup4_i2c_apps_clk	&gcc_blsp1_qup4_i2c_apps_clk
#define clk_gcc_blsp1_qup4_spi_apps_clk	&gcc_blsp1_qup4_spi_apps_clk
#define clk_gcc_blsp1_qup5_i2c_apps_clk	&gcc_blsp1_qup5_i2c_apps_clk
#define clk_gcc_blsp1_qup5_spi_apps_clk	&gcc_blsp1_qup5_spi_apps_clk
#define clk_gcc_blsp1_qup6_i2c_apps_clk	&gcc_blsp1_qup6_i2c_apps_clk
#define clk_gcc_blsp1_qup6_spi_apps_clk	&gcc_blsp1_qup6_spi_apps_clk
#define clk_gcc_blsp1_uart1_apps_clk	&gcc_blsp1_uart1_apps_clk
#define clk_gcc_blsp1_uart2_apps_clk	&gcc_blsp1_uart2_apps_clk
#define clk_gcc_blsp1_uart3_apps_clk	&gcc_blsp1_uart3_apps_clk
#define clk_gcc_blsp1_uart4_apps_clk	&gcc_blsp1_uart4_apps_clk
#define clk_gcc_blsp1_uart5_apps_clk	&gcc_blsp1_uart5_apps_clk
#define clk_gcc_blsp1_uart6_apps_clk	&gcc_blsp1_uart6_apps_clk
#define clk_gcc_blsp2_ahb_clk		&gcc_blsp2_ahb_clk
#define clk_gcc_blsp2_qup1_i2c_apps_clk	&gcc_blsp2_qup1_i2c_apps_clk
#define clk_gcc_blsp2_qup1_spi_apps_clk	&gcc_blsp2_qup1_spi_apps_clk
#define clk_gcc_blsp2_qup2_i2c_apps_clk	&gcc_blsp2_qup2_i2c_apps_clk
#define clk_gcc_blsp2_qup2_spi_apps_clk	&gcc_blsp2_qup2_spi_apps_clk
#define clk_gcc_blsp2_qup3_i2c_apps_clk	&gcc_blsp2_qup3_i2c_apps_clk
#define clk_gcc_blsp2_qup3_spi_apps_clk	&gcc_blsp2_qup3_spi_apps_clk
#define clk_gcc_blsp2_qup4_i2c_apps_clk	&gcc_blsp2_qup4_i2c_apps_clk
#define clk_gcc_blsp2_qup4_spi_apps_clk	&gcc_blsp2_qup4_spi_apps_clk
#define clk_gcc_blsp2_qup5_i2c_apps_clk	&gcc_blsp2_qup5_i2c_apps_clk
#define clk_gcc_blsp2_qup5_spi_apps_clk	&gcc_blsp2_qup5_spi_apps_clk
#define clk_gcc_blsp2_qup6_i2c_apps_clk	&gcc_blsp2_qup6_i2c_apps_clk
#define clk_gcc_blsp2_qup6_spi_apps_clk	&gcc_blsp2_qup6_spi_apps_clk
#define clk_gcc_blsp2_uart1_apps_clk	&gcc_blsp2_uart1_apps_clk
#define clk_gcc_blsp2_uart2_apps_clk	&gcc_blsp2_uart2_apps_clk
#define clk_gcc_blsp2_uart3_apps_clk	&gcc_blsp2_uart3_apps_clk
#define clk_gcc_blsp2_uart4_apps_clk	&gcc_blsp2_uart4_apps_clk
#define clk_gcc_blsp2_uart5_apps_clk	&gcc_blsp2_uart5_apps_clk
#define clk_gcc_blsp2_uart6_apps_clk	&gcc_blsp2_uart6_apps_clk
#define clk_gcc_boot_rom_ahb_clk	&gcc_boot_rom_ahb_clk
#define clk_gcc_gp1_clk			&gcc_gp1_clk
#define clk_gcc_gp2_clk			&gcc_gp2_clk
#define clk_gcc_gp3_clk			&gcc_gp3_clk
#define clk_gcc_imem_axi_clk		&gcc_imem_axi_clk
#define clk_gcc_imem_cfg_ahb_clk	&gcc_imem_cfg_ahb_clk
#define clk_gcc_lpass_q6_axi_clk	&gcc_lpass_q6_axi_clk
#define clk_gcc_lpass_q6_smmu_axi_clk	&gcc_lpass_q6_smmu_axi_clk
#define clk_gcc_lpass_sway_clk		&gcc_lpass_sway_clk
#define clk_gcc_pcie_0_aux_clk		&gcc_pcie_0_aux_clk
#define clk_gcc_pcie_0_cfg_ahb_clk	&gcc_pcie_0_cfg_ahb_clk
#define clk_gcc_pcie_0_mstr_axi_clk	&gcc_pcie_0_mstr_axi_clk
#define clk_gcc_pcie_0_pipe_clk		&gcc_pcie_0_pipe_clk
#define clk_gcc_pcie_0_slv_axi_clk	&gcc_pcie_0_slv_axi_clk
#define clk_gcc_pcie_1_aux_clk		&gcc_pcie_1_aux_clk
#define clk_gcc_pcie_1_cfg_ahb_clk	&gcc_pcie_1_cfg_ahb_clk
#define clk_gcc_pcie_1_mstr_axi_clk	&gcc_pcie_1_mstr_axi_clk
#define clk_gcc_pcie_1_pipe_clk		&gcc_pcie_1_pipe_clk
#define clk_gcc_pcie_1_slv_axi_clk	&gcc_pcie_1_slv_axi_clk
#define clk_gcc_pcie_2_aux_clk		&gcc_pcie_2_aux_clk
#define clk_gcc_pcie_2_cfg_ahb_clk	&gcc_pcie_2_cfg_ahb_clk
#define clk_gcc_pcie_2_mstr_axi_clk	&gcc_pcie_2_mstr_axi_clk
#define clk_gcc_pcie_2_pipe_clk		&gcc_pcie_2_pipe_clk
#define clk_gcc_pcie_2_slv_axi_clk	&gcc_pcie_2_slv_axi_clk
#define clk_gcc_pcie_phy_aux_clk	&gcc_pcie_phy_aux_clk
#define clk_gcc_pcie_phy_cfg_ahb_clk	&gcc_pcie_phy_cfg_ahb_clk
#define clk_gcc_pdm2_clk		&gcc_pdm2_clk
#define clk_gcc_pdm_ahb_clk		&gcc_pdm_ahb_clk
#define clk_gcc_prng_ahb_clk		&gcc_prng_ahb_clk
#define clk_gcc_sdcc1_ahb_clk		&gcc_sdcc1_ahb_clk
#define clk_gcc_sdcc1_apps_clk		&gcc_sdcc1_apps_clk
#define clk_gcc_sdcc2_ahb_clk		&gcc_sdcc2_ahb_clk
#define clk_gcc_sdcc2_apps_clk		&gcc_sdcc2_apps_clk
#define clk_gcc_sdcc3_ahb_clk		&gcc_sdcc3_ahb_clk
#define clk_gcc_sdcc3_apps_clk		&gcc_sdcc3_apps_clk
#define clk_gcc_sdcc4_ahb_clk		&gcc_sdcc4_ahb_clk
#define clk_gcc_sdcc4_apps_clk		&gcc_sdcc4_apps_clk
#define clk_gcc_sys_noc_hs_axi_clk	&gcc_sys_noc_hs_axi_clk
#define clk_gcc_sys_noc_ufs_axi_clk	&gcc_sys_noc_ufs_axi_clk
#define clk_gcc_sys_noc_usb3_axi_clk	&gcc_sys_noc_usb3_axi_clk
#define clk_gcc_tsif_ahb_clk		&gcc_tsif_ahb_clk
#define clk_gcc_tsif_inactivity_timers_clk	&gcc_tsif_inactivity_timers_clk
#define clk_gcc_tsif_ref_clk		&gcc_tsif_ref_clk
#define clk_gcc_ufs_ahb_clk		&gcc_ufs_ahb_clk
#define clk_gcc_ufs_axi_clk		&gcc_ufs_axi_clk
#define clk_gcc_ufs_ice_core_clk	&gcc_ufs_ice_core_clk
#define clk_gcc_ufs_rx_cfg_clk		&gcc_ufs_rx_cfg_clk
#define clk_gcc_ufs_rx_symbol_0_clk	&gcc_ufs_rx_symbol_0_clk
#define clk_gcc_ufs_rx_symbol_1_clk	&gcc_ufs_rx_symbol_1_clk
#define clk_gcc_ufs_tx_cfg_clk		&gcc_ufs_tx_cfg_clk
#define clk_gcc_ufs_tx_symbol_0_clk	&gcc_ufs_tx_symbol_0_clk
#define clk_gcc_ufs_tx_symbol_1_clk	&gcc_ufs_tx_symbol_1_clk
#define clk_gcc_ufs_unipro_core_clk	&gcc_ufs_unipro_core_clk
#define clk_gcc_usb20_master_clk	&gcc_usb20_master_clk
#define clk_gcc_usb20_mock_utmi_clk	&gcc_usb20_mock_utmi_clk
#define clk_gcc_usb20_sleep_clk		&gcc_usb20_sleep_clk
#define clk_gcc_usb30_master_clk	&gcc_usb30_master_clk
#define clk_gcc_usb30_mock_utmi_clk	&gcc_usb30_mock_utmi_clk
#define clk_gcc_usb30_sleep_clk		&gcc_usb30_sleep_clk
#define clk_gcc_usb3_phy_aux_clk	&gcc_usb3_phy_aux_clk
#define clk_gcc_usb3_phy_pipe_clk	&gcc_usb3_phy_pipe_clk
#define clk_gcc_usb_phy_cfg_ahb2phy_clk	&gcc_usb_phy_cfg_ahb2phy_clk
#define clk_gcc_usb3_clkref_clk		&gcc_usb3_clkref_clk
#define clk_gcc_aggre0_cnoc_ahb_clk	&gcc_aggre0_cnoc_ahb_clk
#define clk_gcc_aggre0_noc_at_clk	&gcc_aggre0_noc_at_clk
#define clk_gcc_aggre0_snoc_axi_clk	&gcc_aggre0_snoc_axi_clk
#define clk_gpll0_out_mmsscc		&gpll0_out_mmsscc

/* clock_mmss controlled clocks */
#define clk_mmsscc_xo			0x05e63704
#define clk_mmsscc_gpll0		0xe900c515
#define clk_mmsscc_mmssnoc_ahb		0x7b4bd6f7
#define clk_mmpll0			0xdd83b751
#define clk_mmpll0_out_main		0x2f996a31
#define clk_mmpll1			0x6da7fb90
#define clk_mmpll1_out_main		0xa0d3a7da
#define clk_mmpll4			0x22c063c1
#define clk_mmpll4_out_main		0xfb21c2fd
#define clk_mmpll3			0x18c76899
#define clk_mmpll3_out_main		0x6eb6328f
#define clk_ahb_clk_src			0x86f49203
#define clk_axi_clk_src			0x6617efab
#define clk_mmpll2			0x1190e4d8
#define clk_mmpll2_out_main		0x1e9e24a8
#define clk_mmpll8			0xd06ad45e
#define clk_mmpll8_out_main		0x75b1f386
#define clk_mmpll9			0x1c50684c
#define clk_mmpll9_out_main		0x16b74937
#define clk_mmpll5			0xa41e1936
#define clk_mmpll5_out_main		0xcc1897bf
#define clk_csi0_clk_src		0x227e65bc
#define clk_vfe0_clk_src		0xa0c2bd8f
#define clk_vfe1_clk_src		0x4e357366
#define clk_csi1_clk_src		0x6a2a6c36
#define clk_csi2_clk_src		0x4113589f
#define clk_csi3_clk_src		0xfd934012
#define clk_maxi_clk_src		0x52c09777
#define clk_cpp_clk_src			0x8382f56d
#define clk_jpeg0_clk_src		0x9a0a0ac3
#define clk_jpeg2_clk_src		0x5ad927f3
#define clk_jpeg_dma_clk_src		0xb68afcea
#define clk_mdp_clk_src			0x6dc1f8f1
#define clk_video_core_clk_src		0x8be4c944
#define clk_fd_core_clk_src		0xe4799ab7
#define clk_cci_clk_src			0x822f3d97
#define clk_csiphy0_3p_clk_src		0xd2474b12
#define clk_csiphy1_3p_clk_src		0x46a02aff
#define clk_csiphy2_3p_clk_src		0x1447813f
#define clk_camss_gp0_clk_src		0x6b57cfe6
#define clk_camss_gp1_clk_src		0xf735368a
#define clk_jpeg_dma_clk_src		0xb68afcea
#define clk_mclk0_clk_src		0x266b3853
#define clk_mclk1_clk_src		0xa73cad0c
#define clk_mclk2_clk_src		0x42545468
#define clk_mclk3_clk_src		0x2bfbb714
#define clk_csi0phytimer_clk_src	0xc8a309be
#define clk_csi1phytimer_clk_src	0x7c0fe23a
#define clk_csi2phytimer_clk_src	0x62ffea9c
#define clk_dsa_core_clk_src		0x26f8bb96
#define clk_isense_clk_src		0x6157b336
#define clk_rbbmtimer_clk_src		0x17649ecc
#define clk_edpaux_clk_src		0x02a8ca8f
#define clk_edpgtc_clk_src		0xa51421ce
#define clk_edplink_clk_src		0x3b7f35de
#define clk_edppixel_clk_src		0x76fdb3c5
#define clk_esc0_clk_src		0xb41d7c38
#define clk_esc1_clk_src		0x3b0afa42
#define clk_hdmi_clk_src		0xb40aeea9
#define clk_vsync_clk_src		0xecb43940
#define clk_rbcpr_clk_src		0x2c2e9af2
#define clk_video_subcore0_clk_src	0x88d79636
#define clk_video_subcore1_clk_src	0x4966930c
#define clk_mmss_bto_ahb_clk		0xfdf8c361
#define clk_camss_ahb_clk		0xc4ff91d4
#define clk_camss_cci_ahb_clk		0x04c4441a
#define clk_camss_cci_clk		0xd6cb5eb9
#define clk_camss_cpp_ahb_clk		0x12e9a87b
#define clk_camss_cpp_clk		0xb82f366b
#define clk_camss_cpp_axi_clk		0x5598c804
#define clk_camss_cpp_vbif_ahb_clk	0xb5f31be4
#define clk_camss_csi0_ahb_clk		0x6e29c972
#define clk_camss_csi0_clk		0x30862ddb
#define clk_camss_csi0phy_clk		0x2cecfb84
#define clk_camss_csi0pix_clk		0x6946f77b
#define clk_camss_csi0rdi_clk		0x83645ef5
#define clk_camss_csi1_ahb_clk		0xccc15f06
#define clk_camss_csi1_clk		0xb150f052
#define clk_camss_csi1phy_clk		0xb989f06d
#define clk_camss_csi1pix_clk		0x58d19bf3
#define clk_camss_csi1rdi_clk		0x4d2f3352
#define clk_camss_csi2_ahb_clk		0x92d02d75
#define clk_camss_csi2_clk		0x74fc92e8
#define clk_camss_csi2phy_clk		0xda05d9d8
#define clk_camss_csi2pix_clk		0xf8ed0731
#define clk_camss_csi2rdi_clk		0xdc1b2081
#define clk_camss_csi3_ahb_clk		0xee5e459c
#define clk_camss_csi3_clk		0x39488fdd
#define clk_camss_csi3phy_clk		0x8b6063b9
#define clk_camss_csi3pix_clk		0xd82bd467
#define clk_camss_csi3rdi_clk		0xb6750046
#define clk_camss_csi_vfe0_clk		0x3023937a
#define clk_camss_csi_vfe1_clk		0xe66fa522
#define clk_camss_csiphy0_3p_clk	0xf2a54f5a
#define clk_camss_csiphy1_3p_clk	0x8bf70cb2
#define clk_camss_csiphy2_3p_clk	0x1c14c939
#define clk_camss_gp0_clk		0xcee7e51d
#define clk_camss_gp1_clk		0x41f1c2e3
#define clk_camss_ispif_ahb_clk		0x9a212c6d
#define clk_camss_jpeg0_clk		0x0b0e2db7
#define clk_camss_jpeg2_clk		0xd7291c8d
#define clk_camss_jpeg_ahb_clk		0x1f47fd28
#define clk_camss_jpeg_axi_clk		0x9e5545c8
#define clk_camss_jpeg_dma_clk		0x2336e65d
#define clk_camss_mclk0_clk		0xcf0c61e0
#define clk_camss_mclk1_clk		0xd1410ed4
#define clk_camss_mclk2_clk		0x851286f2
#define clk_camss_mclk3_clk		0x4db11c45
#define clk_camss_micro_ahb_clk		0x33a23277
#define clk_camss_csi0phytimer_clk	0xff93b3c8
#define clk_camss_csi1phytimer_clk	0x6c399ab6
#define clk_camss_csi2phytimer_clk	0x24f47f49
#define clk_camss_top_ahb_clk		0x8f8b2d33
#define clk_camss_vfe_ahb_clk		0x595197bc
#define clk_camss_vfe_axi_clk		0x273d4c31
#define clk_camss_vfe0_ahb_clk		0x4652833c
#define clk_camss_vfe0_clk		0x1e9bb8c4
#define clk_camss_vfe0_stream_clk	0x22835fa4
#define clk_camss_vfe1_ahb_clk		0x6a56abd3
#define clk_camss_vfe1_clk		0x5bffa69b
#define clk_camss_vfe1_stream_clk	0x92f849b9
#define clk_dsa_core_clk		0xd0e5bae2
#define clk_dsa_noc_cfg_ahb_clk		0xec64c02d
#define clk_fd_ahb_clk			0x868a2c5c
#define clk_fd_core_clk			0x3badcae4
#define clk_fd_core_uar_clk		0x7e624e15
#define clk_gpu_ahb_clk			0xf97f1d43
#define clk_gpu_aon_isense_clk		0xa9e9b297
#define clk_gpu_gx_gfx3d_clk		0xb7ece823
#define clk_gpu_gx_rbbmtimer_clk	0xdeba634e
#define clk_mdss_ahb_clk		0x684ccb41
#define clk_mdss_axi_clk		0xcc07d687
#define clk_mdss_edpaux_clk		0x922d79ee
#define clk_mdss_edpgtc_clk		0xccb2e4a4
#define clk_mdss_edplink_clk		0xa04e7500
#define clk_mdss_edppixel_clk		0xb0011f51
#define clk_mdss_esc0_clk		0x28cafbe6
#define clk_mdss_esc1_clk		0xc22c6883
#define clk_mdss_hdmi_ahb_clk		0x01cef516
#define clk_mdss_hdmi_clk		0x097a6de9
#define clk_mdss_mdp_clk		0x618336ac
#define clk_mdss_vsync_clk		0x42a022d3
#define clk_mmss_misc_ahb_clk		0xea30b0e7
#define clk_mmss_misc_cxo_clk		0xe620cd80
#define clk_mmagic_bimc_axi_clk		0xfc9d49d8
#define clk_mmagic_bimc_noc_cfg_ahb_clk 0x12d5ba72
#define clk_mmagic_camss_axi_clk	0xa8b1c16b
#define clk_mmagic_camss_noc_cfg_ahb_clk 0x5182c819
#define clk_throttle_camss_ahb_clk	0x5c3b3b21
#define clk_throttle_camss_axi_clk	0xbaa23c28
#define clk_throttle_camss_cxo_clk	0x93e27c3b
#define clk_mmss_mmagic_cfg_ahb_clk	0x5e94a822
#define clk_mmagic_mdss_axi_clk		0xa0359d10
#define clk_mmagic_mdss_noc_cfg_ahb_clk 0x9c6d5482
#define clk_throttle_mdss_ahb_clk	0x8ae6585f
#define clk_throttle_mdss_axi_clk	0xc7850107
#define clk_throttle_mdss_cxo_clk	0xadb11a10
#define clk_mmagic_video_axi_clk	0x7b9219c3
#define clk_mmagic_video_noc_cfg_ahb_clk 0x5124d256
#define clk_throttle_video_ahb_clk	0x5612a745
#define clk_throttle_video_axi_clk	0x06c344d6
#define clk_throttle_video_cxo_clk	0x808d592e
#define clk_mmss_mmagic_ahb_clk		0x3d15f2b0
#define clk_mmss_mmagic_axi_clk		0x91ae9b77
#define clk_mmss_s0_axi_clk		0xcbd7b001
#define clk_mmss_mmagic_maxi_clk	0xbdaf5af7
#define clk_mmss_rbcpr_ahb_clk		0x623ba55f
#define clk_mmss_rbcpr_clk		0x69a23a6f
#define clk_mmss_spdm_cpp_clk		0xefe35cd2
#define clk_mmss_spdm_jpeg_dma_clk	0xcb7bd5a0
#define clk_smmu_cpp_ahb_clk		0x3ad82d84
#define clk_smmu_cpp_axi_clk		0xa6bb2f4a
#define clk_smmu_jpeg_ahb_clk		0x10c436ec
#define clk_smmu_jpeg_axi_clk		0x41112f37
#define clk_smmu_mdp_ahb_clk		0x04994cb2
#define clk_smmu_mdp_axi_clk		0x7fd71687
#define clk_smmu_rot_ahb_clk		0xa30772c9
#define clk_smmu_rot_axi_clk		0xfed7c078
#define clk_smmu_vfe_ahb_clk		0x4dabebe7
#define clk_smmu_vfe_axi_clk		0xde483725
#define clk_smmu_video_ahb_clk		0x2d738e2c
#define clk_smmu_video_axi_clk		0xe2b5b887
#define clk_video_ahb_clk		0x90775cfb
#define clk_video_axi_clk		0xe6c16dba
#define clk_video_core_clk		0x7e876ec3
#define clk_video_maxi_clk		0x97749db6
#define clk_video_subcore0_clk		0xb6f63e6c
#define clk_video_subcore1_clk		0x26c29cb4
#define clk_vmem_ahb_clk		0xab6223ff
#define clk_vmem_maxi_clk		0x15ef32db
#define clk_mmss_debug_mux		0xe646ffda
#define clk_mmss_gcc_dbg_clk		0xafa4d48a
#define clk_gfx3d_clk_src		0x917f76ef

/* clock_mdss controlled clocks */
#define clk_extpclk_clk_src		0xb2c31abd
#define clk_mdss_byte0_clk		0xf5a03f64
#define clk_mdss_byte1_clk		0xb8c7067d
#define clk_mdss_extpclk_clk		0xfa5aadb0
#define clk_mdss_pclk0_clk		0x3487234a
#define clk_mdss_pclk1_clk		0xd5804246

/* clock_debug controlled clocks */
#define clk_gcc_debug_mux		&gcc_debug_mux

/* external multimedia clocks */
#define clk_pixel0_clk_src		0x669f51aa
#define clk_pixel1_clk_src		0x47c82402
#define clk_byte0_clk_src		0x75cc885b
#define clk_byte1_clk_src		0x63c2c955

#endif
